import { ATTACKS } from '../combat/attacks';
import type { EnemyProfile } from './Enemy';

/** The (very short) cast of enemies. */

export const HOLLOW: EnemyProfile = {
  name: 'Hollow',
  look: {
    scale: 0.97,
    bulk: 0.85,
    skin: 0x6f675b,
    armor: 0x4a4038,
    cloth: 0x3d342b,
    metal: 0x6e6257,
    leather: 0x33291f,
    helmet: 'hollow',
    weapon: 'broken',
    shield: 'none',
    eyes: 0xff8a3a,
    plated: false,
  },
  maxHp: 58,
  maxPoise: 15,
  souls: 55,
  radius: 0.36,
  mass: 0.9,
  walkSpeed: 1.6,
  runSpeed: 3.6,
  turnRate: 5,
  aggroRange: 8.5,
  leash: 14,
  holdRange: 1.6,
  attacks: [
    { attack: ATTACKS.hollowSlash, minRange: 0, maxRange: 2.0, weight: 3 },
    { attack: ATTACKS.hollowFlurry, minRange: 0, maxRange: 1.8, weight: 1.5 },
    { attack: ATTACKS.hollowOverhead, minRange: 0.8, maxRange: 2.4, weight: 1.5 },
  ],
  cooldown: [1.1, 2.4],
  chainChance: 0,
  blocks: false,
  maxStamina: 0,
  blockStaminaFactor: 1,
  backstabbable: true,
  trailColor: 0xb0a090,
};

export const FALLEN_KNIGHT: EnemyProfile = {
  name: 'Fallen Knight',
  look: {
    scale: 1.12,
    bulk: 1.15,
    skin: 0x8a7a6a,
    armor: 0x57493a,
    cloth: 0x252c3a,
    metal: 0x7f848b,
    leather: 0x2c2118,
    helmet: 'knight',
    weapon: 'sword',
    shield: 'tower',
    eyes: 0xff6a2a,
    plated: true,
  },
  maxHp: 190,
  maxPoise: 45,
  souls: 260,
  radius: 0.45,
  mass: 1.6,
  walkSpeed: 1.8,
  runSpeed: 3.4,
  turnRate: 4.5,
  aggroRange: 9,
  leash: 12,
  holdRange: 2.3,
  attacks: [
    { attack: ATTACKS.knightSlash, minRange: 0, maxRange: 2.4, weight: 3 },
    { attack: ATTACKS.knightThrust, minRange: 1.6, maxRange: 3.4, weight: 2 },
    { attack: ATTACKS.knightBash, minRange: 0, maxRange: 1.6, weight: 1.5 },
  ],
  cooldown: [0.9, 2.1],
  chainChance: 0.6,
  blocks: true,
  maxStamina: 110,
  blockStaminaFactor: 0.9,
  backstabbable: true,
  trailColor: 0xd0d8e8,
};

export const ASHEN_WARDEN: EnemyProfile = {
  name: 'The Ashen Warden',
  look: {
    scale: 2.05,
    bulk: 1.25,
    skin: 0x4a3a30,
    armor: 0x2e2a28,
    cloth: 0x3a1410,
    metal: 0x5d5f63,
    leather: 0x1e1612,
    helmet: 'warden',
    weapon: 'greatsword',
    shield: 'none',
    eyes: 0xff5a1a,
    cape: 0x2a0f0c,
    plated: true,
  },
  maxHp: 720,
  maxPoise: 160,
  souls: 3000,
  radius: 0.95,
  mass: 6,
  walkSpeed: 2.3,
  runSpeed: 4.4,
  turnRate: 3.2,
  aggroRange: 99,
  leash: 999,
  holdRange: 3.4,
  attacks: [
    { attack: ATTACKS.wardenSweep, minRange: 0, maxRange: 4.3, weight: 3 },
    { attack: ATTACKS.wardenSlam, minRange: 0, maxRange: 4.2, weight: 2 },
    { attack: ATTACKS.wardenCombo1, minRange: 0, maxRange: 4.2, weight: 2.5 },
    { attack: ATTACKS.wardenLeap, minRange: 6, maxRange: 14, weight: 4 },
    { attack: ATTACKS.wardenFlameSlam, minRange: 0, maxRange: 4.4, weight: 3, minPhase: 2 },
  ],
  cooldown: [0.5, 1.5],
  chainChance: 1,
  blocks: false,
  maxStamina: 0,
  blockStaminaFactor: 1,
  backstabbable: false,
  trailColor: 0xff8a3a,
};
